**Abordagem Estática**

In [ ]:
import pandas as pd
import numpy as np
from collections import OrderedDict
from sklearn.metrics import mean_squared_error as mse

my_dc =OrderedDict({'ARIMA':[0.1,0.2,0.3,0.23,0,1.34,2.34,4.56,0.89,0.42],'SVR':[0.18,0.23,0.37,0.28,0,1.45,2.89,3.56,1.23,1.42],'MLP':[0.17,0.56,0.23,0.78,0.56,1.78,2.23,3.34,1.89,1.23],'Target':[0.37,0.26,0.53,0.68,0.36,1.28,2.73,3.84,1.29,1.53]})
# Zhang, duas colunas : Arima, MLP || Panigrahi, duas colnunas: ETS, MLP
my_metaData = pd.DataFrame(my_dc)

X = my_metaData.iloc[:,0:3]
Y=my_metaData.iloc[:,3]

pesos = np.linalg.pinv(X).dot(Y)# Mínimos quadrados / Least squares


my_dc_teste = OrderedDict({'ARIMA':[0.58,1.2,3.3],'SVR':[1.18,0.78,2.98],'MLP':[1.17,0.56,0.76],'Target_teste':[1.0,0.9,2.0]})
my_metaData_test = pd.DataFrame(my_dc_teste)

X_teste = my_metaData_test.iloc[:,0:3].values
Y_teste = my_metaData_test.iloc[:,3].values

Previsao = X_teste.dot(pesos)

erro_estatico = mse(Y_teste,Previsao)

print(erro_estatico)

0.11847626194929628

In [ ]:
pesos

array([0.0819337 , 0.70206801, 0.25777089])

In [ ]:
my_metaData

   ARIMA   SVR   MLP  Target
0   0.10  0.18  0.17    0.37
1   0.20  0.23  0.56    0.26
2   0.30  0.37  0.23    0.53
3   0.23  0.28  0.78    0.68
4   0.00  0.00  0.56    0.36
5   1.34  1.45  1.78    1.28
6   2.34  2.89  2.23    2.73
7   4.56  3.56  3.34    3.84
8   0.89  1.23  1.89    1.29
9   0.42  1.42  1.23    1.53

In [ ]:
pesos

array([0.0819337 , 0.70206801, 0.25777089])

In [ ]:
my_metaData

   ARIMA   SVR   MLP  Target
0   0.10  0.18  0.17    0.37
1   0.20  0.23  0.56    0.26
2   0.30  0.37  0.23    0.53
3   0.23  0.28  0.78    0.68
4   0.00  0.00  0.56    0.36
5   1.34  1.45  1.78    1.28
6   2.34  2.89  2.23    2.73
7   4.56  3.56  3.34    3.84
8   0.89  1.23  1.89    1.29
9   0.42  1.42  1.23    1.53

**Abordagem Dinâmica**

In [ ]:
import pandas as pd
import numpy as np
from collections import OrderedDict
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import mean_squared_error as mse

my_dc =OrderedDict({'ARIMA':[0.1,0.2,0.3,0.23,0,1.34,2.34,4.56,0.89,0.42],'SVR':[0.18,0.23,0.37,0.28,0,1.45,2.89,3.56,1.23,1.42],'MLP':[0.17,0.56,0.23,0.78,0.56,1.78,2.23,3.34,1.89,1.23],'Target':[0.37,0.26,0.53,0.68,0.36,1.28,2.73,3.84,1.29,1.53]})

my_metaData = pd.DataFrame(my_dc)

X = my_metaData.iloc[:,0:3]
Y=my_metaData.iloc[:,3]

my_dc_teste = OrderedDict({'ARIMA':[0.58,1.2,3.3],'SVR':[1.18,0.78,2.98],'MLP':[1.17,0.56,0.76],'Target_teste':[1.0,0.9,2.0]})
my_metaData_test = pd.DataFrame(my_dc_teste)
Y_teste = my_metaData_test.iloc[:,3].values

knn = NearestNeighbors(n_neighbors=5,metric="euclidean") # K, distancia são parâmetros importantes
knn.fit(X)
previsao_dinamica=[]
for i in range(len(my_metaData_test)):
  X_teste = my_metaData_test.iloc[i,0:3].values

  dists,indexes = knn.kneighbors(X_teste.reshape(1, -1))
  Y_kneighbors = Y[np.ravel(indexes)]
  X_kneighbors = X.iloc[np.ravel(indexes)]






  peso_dinamico = np.linalg.pinv(X_kneighbors).dot(Y_kneighbors)
  previsao_dinamica.append(X_teste.dot(peso_dinamico))



erro_dinamico = mse(Y_teste,previsao_dinamica)
print(erro_dinamico)

0.5007054562226597

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(

In [ ]:
my_metaData_test

   ARIMA   SVR   MLP  Target_teste
0   0.58  1.18  1.17           1.0
1   1.20  0.78  0.56           0.9
2   3.30  2.98  0.76           2.0

In [ ]:
previsao_dinamica

[1.2035164631753532, -11.778311940878993, 3.4884521954198973]

In [ ]:
# abordagem para selecao dinamica

  #predict_svr =SVR.predict(X_kneighbors)
  #predict_mlp = MLP.predict(X_kneighbors)
  #predict_arima = ARIMA.predict(X_kneighbors)

  #mse_svr = mse(Y_kneighbors,predict_svr)
  #mse_mlp = mse(Y_kneighbors,predict_mlp)
  #mse_arima = mse(Y_kneighbors,predict_arima)

  #mdls = ['svr', 'mlp', 'arima']
  #mses = [mse_svr,mse_mlp,mse_arima]

  #indice = np.argmin(mses)

  #preds.append(mlds[indice].predict(X_teste))